#ifndef __MTLK_DOT_CONFIG_H__
#define __MTLK_DOT_CONFIG_H__

/* # */
/* # Automatically generated make config: don't edit */
/* # Linux kernel version: KERNELVERSION */
/* # Tue Jan 17 09:14:10 2012 */
/* # */

/* # */
/* # Metalink WLAN+ configuration */
/* # */
#undef MTCFG_PLATFORM_DONGLE
#define MTCFG_PLATFORM_UGW51_VRX288_NAND (1)
#undef MTCFG_PLATFORM_UGW51_GRX288_NAND
#undef MTCFG_PLATFORM_VB300
#undef MTCFG_PLATFORM_LQ_UGW52_VB300
#undef MTCFG_PLATFORM_GEN35FPGA
#undef MTCFG_PLATFORM_UGW51_VRX288
#undef MTCFG_PLATFORM_UGW51_GW188
#undef MTCFG_PLATFORM_UGW51_ARX188
#undef MTCFG_PLATFORM_UGW51_GRX168
#undef MTCFG_PLATFORM_STAR4MB
#undef MTCFG_PLATFORM_PC_KERN26
#undef MTCFG_PLATFORM_AMCC405EX
#undef MTCFG_PLATFORM_AMCC405_DECA
#define MTCFG_COMPONENTS (1)
#define MTCFG_LIN_DRV (1)
#define MTCFG_LIN_MTTOOLS (1)
#define MTCFG_LIN_RTLOG_COMPONENTS (1)
#undef MTCFG_LIN_DUT
#undef MTCFG_LIN_HELPER_TOOLS
#define MTCFG_BUS_PCI_PCIE (1)
#undef MTCFG_BUS_AHB
#define MTCFG_LINDRV_HW (1)
#define MTCFG_LINDRV_HW_PCIE (1)
#define MTCFG_LINDRV_HW_PCIG3 (1)

/* # */
/* # Features */
/* # */
#define MTCFG_RF_MANAGEMENT_MTLK (1)
#define MTCFG_HOSTAP_06 (1)
#undef MTCFG_WPS_LEDS_ENABLE
#undef MTCFG_FORCE_USE_GENL_DISABLE
#undef MTCFG_IPV4_ONLY_CLI
#undef MTCFG_USE_INTERRUPT_POLLING

/* # */
/* # Debug extentions */
/* # */
#define MTCFG_DEBUG (1)
#undef MTCFG_ENABLE_OBJPOOL
#define MTCFG_TXMM_HISTORY_LENGTH (3)
#undef MTCFG_IRB_DEBUG
#undef MTCFG_CPU_STAT
#undef MTCFG_BENCHMARK_TOOLS
#undef MTCFG_IRB_BENCHMARKING
#undef MTCFG_CCR_DEBUG
#undef MTCFG_FW_WRITE_VALIDATION
#undef MTCFG_TSF_TIMER_TIMESTAMPS_IN_DEBUG_PRINTOUTS
#undef MTCFG_PER_PACKET_STATS
#define MTCFG_NO_FW_RESET_ON_STOP (1)
#undef MTCFG_PCIE_TUNING
#define MTCFG_RT_LOGGER_FUNCTIONS (1)
#undef MTCFG_RT_LOGGER_INLINES

/* # */
/* # Log level */
/* # */
#define MTCFG_MAX_DLEVEL (2)
#undef MTCFG_SILENT
#define MTCFG_USE_GENL_DEF (1)
#define MTCFG_USE_GENL (1)
#undef MTCFG_TSF_TIMER_ACCESS_ENABLED
#define MTCFG_DEVELOPMENT_PLATFORM (1)
#define MTCFG_ENVIRONMENT_NAME "ugw5.1-vrx288-nand"
#define MTCFG_HOST_TYPE "mips-linux"


#endif /* __MTLK_DOT_CONFIG_H__ */
