dnl WARNING:
dnl WARNING: This file is automatically generated from branch_version.m4.in.
dnl WARNING: Do not edit it, all changes will gone.
dnl WARNING: Edit branch_version.m4.in instead.
dnl WARNING:

dnl Definition of the branch version for configure.ac
m4_define([MTLK_BRANCH_VERSION], [3.2.1])
